name: 'Terraform Unit Tests'

on:
  workflow_call:
    inputs:
      runsOnGroup:
        type: string
        default: yorku-shared-runners
      token:
        type: string
        

jobs:
  terraform-unit-tests:
    name: 'Terraform Unit Tests'
    runs-on: 
      group: ${{ inputs.runsOnGroup }}
    
    steps:
    - name: Setup private repo credentials for private modules
      run: git config --global url."https://git:${{ inputs.token }}@github.com/".insteadOf "https://github.com/"

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend=false

    # Validate terraform files
    - name: Terraform Validate
      run: terraform validate

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive

    # Start liniting 
    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: tflint -f compact --module --recursive

      # Perform a security scan of the terraform code using checkov
#    - name: Run Checkov action
#      id: checkov
#      uses: bridgecrewio/checkov-action@master
#      with: 
#        framework: terraform
    - name: Run checkov
      run: checkov -d . --download-external-modules true -o cli -o sarif --framework terraform
      env:
        GITHUB_PAT: ${{ github.token }}

    # Upload results to GitHub Advanced Security
    #- name: Upload SARIF file
    #  if: success() || failure()
    #  uses: github/codeql-action/upload-sarif@v2
    #  with:
    #    sarif_file: results.sarif
    #    category: checkov
